// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TOOLS 3 — text utilities, pure JS, zero dependencies
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function need(args) { return !args.length; }

module.exports = [
    { name: "reverse", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .reverse text" }); await sock.sendMessage(from, { text: args.join(" ").split("").reverse().join("") }); } },
    { name: "uppercase", aliases: ["upper"], async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .uppercase text" }); await sock.sendMessage(from, { text: args.join(" ").toUpperCase() }); } },
    { name: "lowercase", aliases: ["lower"], async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .lowercase text" }); await sock.sendMessage(from, { text: args.join(" ").toLowerCase() }); } },
    { name: "binary", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .binary text" }); const out = args.join(" ").split("").map(c => c.charCodeAt(0).toString(2).padStart(8, "0")).join(" "); await sock.sendMessage(from, { text: out }); } },
    { name: "unbinary", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .unbinary 01000001 ..." }); try { const out = args.join("").split(" ").filter(Boolean).map(b => String.fromCharCode(parseInt(b, 2))).join(""); await sock.sendMessage(from, { text: out || "❌ Invalid binary." }); } catch (e) { await sock.sendMessage(from, { text: "❌ Invalid binary." }); } } },
    { name: "hex", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .hex text" }); const out = Buffer.from(args.join(" "), "utf8").toString("hex"); await sock.sendMessage(from, { text: out }); } },
    { name: "unhex", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .unhex 48656c6c6f" }); try { const out = Buffer.from(args.join(""), "hex").toString("utf8"); await sock.sendMessage(from, { text: out || "❌ Invalid hex." }); } catch (e) { await sock.sendMessage(from, { text: "❌ Invalid hex." }); } } },
    { name: "base64encode", aliases: ["b64encode"], async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .base64encode text" }); await sock.sendMessage(from, { text: Buffer.from(args.join(" "), "utf8").toString("base64") }); } },
    { name: "base64decode", aliases: ["b64decode"], async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .base64decode <base64>" }); try { await sock.sendMessage(from, { text: Buffer.from(args.join(""), "base64").toString("utf8") }); } catch (e) { await sock.sendMessage(from, { text: "❌ Invalid base64." }); } } },
    { name: "morse", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .morse text" }); const M = {A:".-",B:"-...",C:"-.-.",D:"-..",E:".",F:"..-.",G:"--.",H:"....",I:"..",J:".---",K:"-.-",L:".-..",M:"--",N:"-.",O:"---",P:".--.",Q:"--.-",R:".-.",S:"...",T:"-",U:"..-",V:"...-",W:".--",X:"-..-",Y:"-.--",Z:"--..","0":"-----","1":".----","2":"..---","3":"...--","4":"....-","5":".....","6":"-....","7":"--...","8":"---..","9":"----."}; const out = args.join(" ").toUpperCase().split("").map(c => M[c] || (c === " " ? "/" : c)).join(" "); await sock.sendMessage(from, { text: out }); } },
    { name: "upsidedown", aliases: ["flip"], async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .upsidedown text" }); const M = {a:"ɐ",b:"q",c:"ɔ",d:"p",e:"ǝ",f:"ɟ",g:"ƃ",h:"ɥ",i:"ᴉ",j:"ɾ",k:"ʞ",l:"l",m:"ɯ",n:"u",o:"o",p:"d",q:"b",r:"ɹ",s:"s",t:"ʇ",u:"n",v:"ʌ",w:"ʍ",x:"x",y:"ʎ",z:"z"}; const out = args.join(" ").toLowerCase().split("").reverse().map(c => M[c] || c).join(""); await sock.sendMessage(from, { text: out }); } },
    { name: "smallcaps", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .smallcaps text" }); const M = {a:"ᴀ",b:"ʙ",c:"ᴄ",d:"ᴅ",e:"ᴇ",f:"ꜰ",g:"ɢ",h:"ʜ",i:"ɪ",j:"ᴊ",k:"ᴋ",l:"ʟ",m:"ᴍ",n:"ɴ",o:"ᴏ",p:"ᴘ",q:"ǫ",r:"ʀ",s:"s",t:"ᴛ",u:"ᴜ",v:"ᴠ",w:"ᴡ",x:"x",y:"ʏ",z:"ᴢ"}; const out = args.join(" ").toLowerCase().split("").map(c => M[c] || c).join(""); await sock.sendMessage(from, { text: out }); } },
    { name: "bubble", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .bubble text" }); const M = {a:"ⓐ",b:"ⓑ",c:"ⓒ",d:"ⓓ",e:"ⓔ",f:"ⓕ",g:"ⓖ",h:"ⓗ",i:"ⓘ",j:"ⓙ",k:"ⓚ",l:"ⓛ",m:"ⓜ",n:"ⓝ",o:"ⓞ",p:"ⓟ",q:"ⓠ",r:"ⓡ",s:"ⓢ",t:"ⓣ",u:"ⓤ",v:"ⓥ",w:"ⓦ",x:"ⓧ",y:"ⓨ",z:"ⓩ"}; const out = args.join(" ").toLowerCase().split("").map(c => M[c] || c).join(""); await sock.sendMessage(from, { text: out }); } },
    { name: "wordcount", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .wordcount text" }); const text = args.join(" "); await sock.sendMessage(from, { text: `📊 Words: ${text.split(/\s+/).filter(Boolean).length}\nCharacters: ${text.length}` }); } },
    { name: "palindrome", async execute(sock, from, args) { if (need(args)) return sock.sendMessage(from, { text: "❌ .palindrome text" }); const clean = args.join("").toLowerCase().replace(/[^a-z0-9]/g, ""); const isPal = clean === clean.split("").reverse().join(""); await sock.sendMessage(from, { text: isPal ? "✅ That's a palindrome!" : "❌ Not a palindrome." }); } },
    { name: "randomnum", aliases: ["rng"], async execute(sock, from, args) { const min = parseInt(args[0], 10) || 1; const max = parseInt(args[1], 10) || 100; await sock.sendMessage(from, { text: `🎲 ${Math.floor(Math.random() * (max - min + 1)) + min}` }); } },
    { name: "choose", async execute(sock, from, args) { if (args.length < 2) return sock.sendMessage(from, { text: "❌ .choose option1 option2 option3..." }); await sock.sendMessage(from, { text: "👉 " + args[Math.floor(Math.random() * args.length)] }); } },
    { name: "password", aliases: ["genpass"], async execute(sock, from, args) { const len = Math.min(Math.max(parseInt(args[0], 10) || 12, 6), 64); const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*"; let out = ""; for (let i = 0; i < len; i++) out += chars[Math.floor(Math.random() * chars.length)]; await sock.sendMessage(from, { text: "🔐 " + out }); } }
];
